version: '3.7'

services:
  postgres:
    image: 'postgres:10-alpine'
    environment:
      - POSTGRES_USER=cowsay
      - POSTGRES_PASSWORD=cowsay
    volumes:
      - 'postgres:/var/lib/postgresql/data'
    ports:
      - '5432:5432'
 
  backend:
    environment:
      - PYTHONUNBUFFERED='true'
      - PYTHONDONTWRITEBYTECODE=1
      - DATABASE_URL=postgresql://cowsay:cowsay@postgres:5432/cowsay
    build:
      dockerfile: ./backend/Dockerfile
      context: .
    command: >
      gunicorn -b 0.0.0.0:8001
        --access-logfile -
        --reload
        "cow_say.app:create_app()"
    depends_on:
      - postgres
    volumes:
      - './backend:/app'
    ports:
      - '8001:8001'

  frontend:
    environment:
      - PYTHONUNBUFFERED='true'
      - PYTHONDONTWRITEBYTECODE=1
      - BACKEND_URL=http://backend:8001/
    build:
      dockerfile: ./frontend/Dockerfile
      context: .
    command: >
      gunicorn -b 0.0.0.0:8000
        --access-logfile -
        --reload
        "cow_say.app:create_app()"
    depends_on:
      - backend
    volumes:
      - './frontend:/app'
    ports:
      - '8000:8000'


volumes:
  postgres:
